# Generated by Django 5.1.1 on 2024-11-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_user_id', models.IntegerField(default=0)),
                ('player1_user_name', models.CharField(default='Player1', max_length=30)),
                ('player1_score', models.IntegerField(default=0)),
                ('player1_nickname', models.CharField(default='Player1', max_length=30)),
                ('player2_user_id', models.IntegerField(default=0)),
                ('player2_user_name', models.CharField(default='Player2', max_length=30)),
                ('player2_score', models.IntegerField(default=0)),
                ('player2_nickname', models.CharField(default='Player2', max_length=30)),
                ('player3_user_id', models.IntegerField(default=0)),
                ('player3_user_name', models.CharField(default='Player3', max_length=30)),
                ('player3_score', models.IntegerField(default=0)),
                ('player3_nickname', models.CharField(default='Player3', max_length=30)),
                ('player4_user_id', models.IntegerField(default=0)),
                ('player4_user_name', models.CharField(default='Player4', max_length=30)),
                ('player4_score', models.IntegerField(default=0)),
                ('player4_nickname', models.CharField(default='Player4', max_length=30)),
                ('match_type', models.CharField(choices=[('1v1', '1 vs 1'), ('2v2', '2 vs 2')], default='1v1', max_length=10)),
                ('game_type', models.CharField(choices=[('pong', 'Pong'), ('snake', 'Snake')], default='pong', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for all the players'), ('playing', 'Game in progress'), ('finished', 'Game finished')], default='waiting', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
