# Generated by Django 5.1.1 on 2024-11-04 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('nickname', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_nickname',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_user_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_user_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_nickname',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_user_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_user_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player3_nickname',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player3_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player3_user_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player3_user_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player4_nickname',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player4_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player4_user_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player4_user_name',
        ),
        migrations.AddField(
            model_name='tournament',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(choices=[('pong', 'Pong'), ('snake', 'Snake')], default='pong', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_type',
            field=models.CharField(choices=[('1v1', '1 vs 1'), ('2v2', '2 vs 2')], default='1v1', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for all the players'), ('playing', 'Game in progress'), ('finished', 'Game finished')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', to='game_app.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', to='game_app.player'),
        ),
    ]
