# Generated by Django 5.1.1 on 2024-11-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_player_remove_game_player1_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.ManyToManyField(related_name='tournaments', to='game_app.game'),
        ),
    ]
