# Generated by Django 5.1.1 on 2024-11-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_game_tournament_id_tournament_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_custom_name',
            field=models.CharField(default='game_custom_name', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='score_to_win',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
    ]
