# Generated by Django 5.1.1 on 2024-11-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_tournament_tournament_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='score_to_win',
            field=models.IntegerField(default=3),
        ),
    ]
