# Generated by Django 5.1.1 on 2024-11-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0007_tournament_score_to_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_index',
            field=models.IntegerField(default=0),
        ),
    ]
