# Generated by Django 5.1.1 on 2024-11-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0008_player_player_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for all the players'), ('playing', 'Game in progress'), ('ready_to_play', 'Ready to play'), ('finished', 'Game finished')], default='waiting', max_length=20),
        ),
    ]
