# Generated by Django 5.1.1 on 2024-11-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0009_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
