# Generated by Django 5.1.1 on 2024-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0010_player_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='game',
            name='color_ball',
            field=models.CharField(default='#E48D2D', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='color_board',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='color_paddle',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='color_wall',
            field=models.CharField(default='#E48D2D', max_length=7),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ball_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='color_ball',
            field=models.CharField(default='#E48D2D', max_length=7),
        ),
        migrations.AddField(
            model_name='tournament',
            name='color_board',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='tournament',
            name='color_paddle',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='tournament',
            name='color_wall',
            field=models.CharField(default='#E48D2D', max_length=7),
        ),
    ]
