version: '3.8'

services:
  db_prod:
    image: postgres:13
    container_name: ft_transcendence_db_prod_1
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web_prod:
    container_name: ft_transcendence_web_prod_1
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    depends_on:
      - db_prod
    environment:
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data: