
services:
  # Base de données authentification
  auth-db-service:
    container_name: auth_db
    image: postgres:latest
    volumes:
      - ./databases/auth_db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - ./backend/authentification/.env
    networks:
      - internal_network

  # Backend authentification
  auth-service:
    container_name: auth_container
    build:
      context: ./backend/authentification
      dockerfile: Dockerfile
    depends_on:
      - auth-db-service
    volumes:
      - ./backend/authentification:/auth
      - auth:/app/media
    ports:
      - 8000:8000
    env_file:
      - ./backend/authentification/.env
    networks:
      - internal_network
      - redis_network

  # Base de données game
  game-db-service:
    container_name: game_db
    image: postgres:latest
    volumes:
      - ./databases/game_db_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    env_file:
      - ./backend/game/.env
    networks:
      - internal_network

  # Backend game
  game-service:
    container_name: game_container
    build:
      context: ./backend/game
      dockerfile: Dockerfile
    depends_on:
      - game-db-service
    volumes:
      - ./backend/game:/app
    ports:
      - 8001:8001
      - "5678:5678"  # Debugger port
    env_file:
      - ./backend/game/.env
    networks:
      - internal_network
      - redis_network

  # Frontend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - auth-service
      - game-service
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173

  # Génération des certificats SSL
  certificates:
    image: alpine:latest
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx:/scripts
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache openssl && chmod +x ./scripts/generate_ssl_cert.sh && /scripts/generate_ssl_cert.sh"]
    profiles:
      - generate-certificates

  # Nginx
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - frontend
      - auth-service
      - game-service
    networks:
      - internal_network

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - redis_network

networks:
  internal_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:

  auth:
