# Generated by Django 5.1.3 on 2024-11-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
    ]
